//! Typed parsing for the first promoted voice commands.
//!
//! Discord's command catalog remains generated by the Node definitions. This module accepts a
//! Serenity payload only after that contract has validated the root, type and subcommand path.
//! It deliberately does not synthesize, join, or reply; callers decide when the Rust handler is
//! sufficiently complete to own the interaction.

use serenity::model::application::{CommandData, CommandDataOptionValue};
use thiserror::Error;
use vozen_contracts::ContractError;

use crate::{CommandArea, command_path_from_options, route_command};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CoreVoiceCommand {
    Join,
    Leave,
    /// `/laugh` uses the caller's resolved voice but otherwise shares the core call path.
    Laugh,
    /// `/joke` chooses a language-specific voice and optionally appends a delayed laugh.
    Joke {
        language: String,
        laughter: bool,
    },
    Skip,
    ShutUp,
    /// The raw argument is kept only for this interaction. Cleaning, rate limiting and all
    /// durable preference resolution happen in the later speech pipeline.
    Tts {
        text: String,
    },
    /// `/voice preview` is an explicitly requested sample and therefore uses the same-call
    /// admission, bounded queue and synthesis path as `/tts`.
    VoicePreview {
        model: Option<String>,
    },
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum CoreVoiceCommandError {
    #[error("incoming command does not match the registered command contract: {0}")]
    Contract(#[from] ContractError),
    #[error("the promoted voice command is missing its required text option")]
    MissingText,
    #[error("the promoted voice command has a non-string text option")]
    InvalidText,
    #[error("the promoted voice command contains an undeclared option")]
    UnexpectedOption,
    #[error("the joke command is missing its required language option")]
    MissingLanguage,
    #[error("the joke command has a non-string language option")]
    InvalidLanguage,
    #[error("the joke command is missing its required laughter option")]
    MissingLaughter,
    #[error("the joke command has a non-boolean laughter option")]
    InvalidLaughter,
}

/// Parses only the promoted root commands. A contract-valid command from another area, or a
/// core command that has not yet reached parity (`/tts-file`, etc.), returns `None`
/// instead of being accidentally consumed by the Rust runtime.
pub fn parse_promoted_core_voice(
    command: &CommandData,
) -> Result<Option<CoreVoiceCommand>, CoreVoiceCommandError> {
    let path = command_path_from_options(&command.options);
    let area = route_command(&command.name, command.kind.into(), &path)?;
    if command.name == "voice" && path == ["preview"] {
        if area != CommandArea::Personal {
            return Ok(None);
        }
        return parse_voice_preview(&command.options).map(Some);
    }
    if area != CommandArea::CoreVoice
        && !(matches!(command.name.as_str(), "laugh" | "joke") && area == CommandArea::Fun)
    {
        return Ok(None);
    }
    match command.name.as_str() {
        "join" => Ok(Some(CoreVoiceCommand::Join)),
        "leave" => Ok(Some(CoreVoiceCommand::Leave)),
        "laugh" => Ok(Some(CoreVoiceCommand::Laugh)),
        "joke" => parse_joke(&command.options).map(Some),
        "skip" => Ok(Some(CoreVoiceCommand::Skip)),
        "shut-up" => Ok(Some(CoreVoiceCommand::ShutUp)),
        "tts" => {
            if command.options.iter().any(|option| option.name != "text") {
                return Err(CoreVoiceCommandError::UnexpectedOption);
            }
            command
                .options
                .iter()
                .find(|option| option.name == "text")
                .map(|option| match &option.value {
                    CommandDataOptionValue::String(text) => {
                        Ok(Some(CoreVoiceCommand::Tts { text: text.clone() }))
                    }
                    _ => Err(CoreVoiceCommandError::InvalidText),
                })
                .unwrap_or(Err(CoreVoiceCommandError::MissingText))
        }
        _ => Ok(None),
    }
}

fn parse_joke(
    options: &[serenity::model::application::CommandDataOption],
) -> Result<CoreVoiceCommand, CoreVoiceCommandError> {
    if options.len() != 2
        || options
            .iter()
            .any(|option| option.name != "language" && option.name != "laughter")
    {
        return Err(CoreVoiceCommandError::UnexpectedOption);
    }
    let language = options
        .iter()
        .find(|option| option.name == "language")
        .ok_or(CoreVoiceCommandError::MissingLanguage)
        .and_then(|option| match &option.value {
            CommandDataOptionValue::String(language) => Ok(language.clone()),
            _ => Err(CoreVoiceCommandError::InvalidLanguage),
        })?;
    let laughter = options
        .iter()
        .find(|option| option.name == "laughter")
        .ok_or(CoreVoiceCommandError::MissingLaughter)
        .and_then(|option| match option.value {
            CommandDataOptionValue::Boolean(laughter) => Ok(laughter),
            _ => Err(CoreVoiceCommandError::InvalidLaughter),
        })?;
    Ok(CoreVoiceCommand::Joke { language, laughter })
}

fn parse_voice_preview(
    options: &[serenity::model::application::CommandDataOption],
) -> Result<CoreVoiceCommand, CoreVoiceCommandError> {
    if options.iter().any(|option| option.name != "preview") || options.len() != 1 {
        return Err(CoreVoiceCommandError::UnexpectedOption);
    }
    let serenity::model::application::CommandDataOptionValue::SubCommand(options) =
        &options[0].value
    else {
        return Err(CoreVoiceCommandError::UnexpectedOption);
    };
    if options.len() > 1 || options.iter().any(|option| option.name != "model") {
        return Err(CoreVoiceCommandError::UnexpectedOption);
    }
    let model = options
        .first()
        .map(|option| {
            let serenity::model::application::CommandDataOptionValue::String(model) = &option.value
            else {
                return Err(CoreVoiceCommandError::InvalidText);
            };
            Ok(model.clone())
        })
        .transpose()?;
    Ok(CoreVoiceCommand::VoicePreview { model })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn command(payload: &str) -> CommandData {
        serde_json::from_str(payload).expect("valid Discord command payload")
    }

    #[test]
    fn parses_only_the_promoted_core_voice_commands_after_contract_validation() {
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"join","type":1,"options":[]}"#
            ))
            .expect("join"),
            Some(CoreVoiceCommand::Join)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"leave","type":1,"options":[]}"#
            ))
            .expect("leave"),
            Some(CoreVoiceCommand::Leave)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"laugh","type":1,"options":[]}"#
            ))
            .expect("laugh"),
            Some(CoreVoiceCommand::Laugh)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"joke","type":1,"options":[{"name":"language","type":3,"value":"pt"},{"name":"laughter","type":5,"value":true}]}"#
            ))
            .expect("joke"),
            Some(CoreVoiceCommand::Joke { language: "pt".into(), laughter: true })
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"skip","type":1,"options":[]}"#
            ))
            .expect("skip"),
            Some(CoreVoiceCommand::Skip)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"shut-up","type":1,"options":[]}"#
            ))
            .expect("shut-up"),
            Some(CoreVoiceCommand::ShutUp)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts","type":1,"options":[{"name":"text","type":3,"value":"  Olá  "}]}"#,
            ))
            .expect("tts"),
            Some(CoreVoiceCommand::Tts {
                text: "  Olá  ".into()
            })
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"voice","type":1,"options":[{"name":"preview","type":1,"options":[{"name":"model","type":3,"value":"en_US-amy-medium"}]}]}"#,
            ))
            .expect("voice preview"),
            Some(CoreVoiceCommand::VoicePreview {
                model: Some("en_US-amy-medium".into())
            })
        );
        assert_eq!(
            parse_promoted_core_voice(&command(r#"{"id":"1","name":"queue","type":1,"options":[{"name":"show","type":1,"options":[]}]}"#))
                .expect("other area"),
            None
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts-file","type":1,"options":[]}"#
            ))
            .expect("unpromoted core command"),
            None
        );
    }

    #[test]
    fn rejects_missing_forged_or_wrong_type_tts_arguments() {
        assert_eq!(
            parse_promoted_core_voice(&command(r#"{"id":"1","name":"tts","type":1,"options":[]}"#)),
            Err(CoreVoiceCommandError::MissingText)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts","type":1,"options":[{"name":"text","type":4,"value":42}]}"#
            )),
            Err(CoreVoiceCommandError::InvalidText)
        );
        assert!(matches!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts","type":1,"options":[{"name":"made-up","type":3,"value":"hello"}]}"#
            )),
            Err(CoreVoiceCommandError::UnexpectedOption)
        ));
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"voice","type":1,"options":[{"name":"preview","type":1,"options":[{"name":"model","type":4,"value":42}]}]}"#,
            )),
            Err(CoreVoiceCommandError::InvalidText)
        );
    }

    #[test]
    fn rejects_missing_or_forged_joke_arguments() {
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"joke","type":1,"options":[]}"#
            )),
            Err(CoreVoiceCommandError::UnexpectedOption)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"joke","type":1,"options":[{"name":"language","type":3,"value":"pt"},{"name":"laughter","type":3,"value":"yes"}]}"#
            )),
            Err(CoreVoiceCommandError::InvalidLaughter)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"joke","type":1,"options":[{"name":"language","type":4,"value":1},{"name":"laughter","type":5,"value":false}]}"#
            )),
            Err(CoreVoiceCommandError::InvalidLanguage)
        );
    }
}
