//! Typed parsing for the first promoted voice commands.
//!
//! Discord's command catalog remains generated by the Node definitions. This module accepts a
//! Serenity payload only after that contract has validated the root, type and subcommand path.
//! It deliberately does not synthesize, join, or reply; callers decide when the Rust handler is
//! sufficiently complete to own the interaction.

use serenity::model::application::{CommandData, CommandDataOptionValue};
use thiserror::Error;
use vozen_contracts::ContractError;

use crate::{CommandArea, command_path_from_options, route_command};

#[derive(Debug, Clone, PartialEq, Eq)]
pub enum CoreVoiceCommand {
    Join,
    Leave,
    Skip,
    ShutUp,
    /// The raw argument is kept only for this interaction. Cleaning, rate limiting and all
    /// durable preference resolution happen in the later speech pipeline.
    Tts {
        text: String,
    },
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum CoreVoiceCommandError {
    #[error("incoming command does not match the registered command contract: {0}")]
    Contract(#[from] ContractError),
    #[error("the promoted voice command is missing its required text option")]
    MissingText,
    #[error("the promoted voice command has a non-string text option")]
    InvalidText,
    #[error("the promoted voice command contains an undeclared option")]
    UnexpectedOption,
}

/// Parses only the promoted root commands. A contract-valid command from another area, or a
/// core command that has not yet reached parity (`/tts-file`, etc.), returns `None`
/// instead of being accidentally consumed by the Rust runtime.
pub fn parse_promoted_core_voice(
    command: &CommandData,
) -> Result<Option<CoreVoiceCommand>, CoreVoiceCommandError> {
    let path = command_path_from_options(&command.options);
    if route_command(&command.name, command.kind.into(), &path)? != CommandArea::CoreVoice {
        return Ok(None);
    }
    match command.name.as_str() {
        "join" => Ok(Some(CoreVoiceCommand::Join)),
        "leave" => Ok(Some(CoreVoiceCommand::Leave)),
        "skip" => Ok(Some(CoreVoiceCommand::Skip)),
        "shut-up" => Ok(Some(CoreVoiceCommand::ShutUp)),
        "tts" => {
            if command.options.iter().any(|option| option.name != "text") {
                return Err(CoreVoiceCommandError::UnexpectedOption);
            }
            command
                .options
                .iter()
                .find(|option| option.name == "text")
                .map(|option| match &option.value {
                    CommandDataOptionValue::String(text) => {
                        Ok(Some(CoreVoiceCommand::Tts { text: text.clone() }))
                    }
                    _ => Err(CoreVoiceCommandError::InvalidText),
                })
                .unwrap_or(Err(CoreVoiceCommandError::MissingText))
        }
        _ => Ok(None),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn command(payload: &str) -> CommandData {
        serde_json::from_str(payload).expect("valid Discord command payload")
    }

    #[test]
    fn parses_only_the_promoted_core_voice_commands_after_contract_validation() {
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"join","type":1,"options":[]}"#
            ))
            .expect("join"),
            Some(CoreVoiceCommand::Join)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"leave","type":1,"options":[]}"#
            ))
            .expect("leave"),
            Some(CoreVoiceCommand::Leave)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"skip","type":1,"options":[]}"#
            ))
            .expect("skip"),
            Some(CoreVoiceCommand::Skip)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"shut-up","type":1,"options":[]}"#
            ))
            .expect("shut-up"),
            Some(CoreVoiceCommand::ShutUp)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts","type":1,"options":[{"name":"text","type":3,"value":"  Olá  "}]}"#,
            ))
            .expect("tts"),
            Some(CoreVoiceCommand::Tts {
                text: "  Olá  ".into()
            })
        );
        assert_eq!(
            parse_promoted_core_voice(&command(r#"{"id":"1","name":"queue","type":1,"options":[{"name":"show","type":1,"options":[]}]}"#))
                .expect("other area"),
            None
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts-file","type":1,"options":[]}"#
            ))
            .expect("unpromoted core command"),
            None
        );
    }

    #[test]
    fn rejects_missing_forged_or_wrong_type_tts_arguments() {
        assert_eq!(
            parse_promoted_core_voice(&command(r#"{"id":"1","name":"tts","type":1,"options":[]}"#)),
            Err(CoreVoiceCommandError::MissingText)
        );
        assert_eq!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts","type":1,"options":[{"name":"text","type":4,"value":42}]}"#
            )),
            Err(CoreVoiceCommandError::InvalidText)
        );
        assert!(matches!(
            parse_promoted_core_voice(&command(
                r#"{"id":"1","name":"tts","type":1,"options":[{"name":"made-up","type":3,"value":"hello"}]}"#
            )),
            Err(CoreVoiceCommandError::UnexpectedOption)
        ));
    }
}
