import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { GAME_DEFS } from '../src/games/index';

const target = path.resolve('crates/vozen-discord/src/generated_game_catalog.rs');
const check = process.argv.includes('--check');

function rustString(value: string): string {
  return JSON.stringify(value);
}

function render(): string {
  const entries = GAME_DEFS.map((game) => {
    const premium = game.premium === true;
    const usesLanguage = game.usesLanguage === true;
    return `    definition(\n        ${rustString(game.id)},\n        ${rustString(game.nameKey)},\n        ${rustString(game.descKey)},\n        ${String(game.needsVoice)},\n        ${String(premium)},\n        ${String(usesLanguage)},\n    ),`;
  }).join('\n');

  return (
    `// @generated by tools/export-rust-game-catalog.ts — do not edit manually.\n\n` +
    `pub const GAME_CATALOG: &[GameDefinition] = &[\n${entries}\n];\n\n` +
    `const fn definition(\n    id: &'static str,\n    name_key: &'static str,\n    desc_key: &'static str,\n    needs_voice: bool,\n    premium: bool,\n    uses_language: bool,\n) -> GameDefinition {\n    GameDefinition {\n        id,\n        name_key,\n        desc_key,\n        needs_voice,\n        premium,\n        uses_language,\n    }\n}\n`
  );
}

function main(): void {
  const expected = render();
  if (check) {
    const actual = existsSync(target) ? readFileSync(target, 'utf8') : '';
    if (actual !== expected) {
      console.error('Rust game catalog contract is stale. Run: npm run build:rust-game-catalog');
      process.exitCode = 1;
    }
    return;
  }
  mkdirSync(path.dirname(target), { recursive: true });
  writeFileSync(target, expected, 'utf8');
  console.log(`Wrote ${path.relative(process.cwd(), target)}`);
}

main();
