[package]
name = "vozen-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
axum.workspace = true
thiserror.workspace = true
tokio.workspace = true
vozen-api = { path = "../vozen-api" }
vozen-core = { path = "../vozen-core" }
vozen-discord = { path = "../vozen-discord" }
vozen-store = { path = "../vozen-store" }

[lints]
workspace = true
